# Generated by Django 5.1.3 on 2024-12-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdrn_app_new', '0002_blooddonation_incident_remove_resource_disaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='available_for',
            field=models.CharField(choices=[('General', 'General'), ('Disaster Relief', 'Disaster Relief'), ('Medical Aid', 'Medical Aid'), ('Food Distribution', 'Food Distribution'), ('Shelter Assistance', 'Shelter Assistance'), ('Logistics Support', 'Logistics Support'), ('Other', 'Other')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
