# Generated by Django 5.1.3 on 2024-12-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdrn_app_new', '0003_alter_volunteer_available_for_alter_volunteer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
