# Generated by Django 5.1.3 on 2024-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdrn_app_new', '0004_blooddonation_status_alter_blooddonation_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
    ]
