# Generated by Django 5.1.3 on 2024-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdrn_app_new', '0005_incident_incident_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident_image',
        ),
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
    ]
